on: [push, pull_request]

name: Continuous integration

jobs:
  primary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy

      - run: cargo build

      - run: cargo test

      - run: cargo fmt --all -- --check

      - run: cargo clippy -- -D warnings

  secondary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - beta
          - nightly
          - 1.31.0

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - run: cargo update

      # This is the version last compatible with 1.31
      - run: cargo update -p backtrace --precise 0.3.35
        if: matrix.rust == '1.31.0'

      - run: cargo build

      # It's not worth making the tests run on 1.31 -- building the
      # code is enough.
      - run: cargo test
        if: matrix.rust != '1.31.0'

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        rust:
          - stable

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - run: cargo build

      - run: cargo test
